version: '3.8'

services:
  # NODE APPLICATION 1
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oasis_app_node1
    restart: unless-stopped
    environment:
      - APP_NODE_NAME=WEB NODE 1
      - APP_NODE_COLOR=#22c55e
    volumes:
      - .:/var/www
    networks:
      - oasis_ujikom_net

  # NODE APPLICATION 2
  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oasis_app_node2
    restart: unless-stopped
    environment:
      - APP_NODE_NAME=WEB NODE 2
      - APP_NODE_COLOR=#f59e0b
    volumes:
      - .:/var/www
    networks:
      - oasis_ujikom_net

  # NODE APPLICATION 3
  web3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oasis_app_node3
    restart: unless-stopped
    environment:
      - APP_NODE_NAME=WEB NODE 3
      - APP_NODE_COLOR=#a855f7
    volumes:
      - .:/var/www
    networks:
      - oasis_ujikom_net

  # NGINX EDGE REVERSE PROXY & BALANCER
  loadbalancer:
    image: nginx:alpine
    container_name: oasis_loadbalancer_8080
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker-compose/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - oasis_ujikom_net

  # PERSISTENT DATABASE ENGINE
  db:
    image: postgres:16-alpine
    container_name: oasis_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: oasis_db
      POSTGRES_USER: oasis_admin
      POSTGRES_PASSWORD: SecretPassword123
    volumes:
      - oasis_db_persistent_data:/var/lib/postgresql/data
    networks:
      - oasis_ujikom_net

networks:
  oasis_ujikom_net:
    driver: bridge

volumes:
  oasis_db_persistent_data:
    driver: local