upstream laravel_php_fpm_cluster {
    least_conn; # Membagi traffic ke kontainer yang paling sedikit menangani koneksi aktif
    server web1:9000;
    server web2:9000;
    server web3:9000;
}

server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    root /var/www/public;
    index index.php index.html;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Teruskan request backend ke PHP-FPM Cluster Alpine
    location ~ \.php$ {
        fastcgi_pass laravel_php_fpm_cluster;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires max;
        log_not_found off;
    }
}